import TColor from "./TColor";
import { X11ColorNames } from "./X11";

/**
 * Returns the color for the given name
 * @param {String} name
 * @return color or undefined if name not found
 */
declare function getForName(name: X11ColorNames): TColor;
declare function getForName(name: string): TColor;

/**
 * Return the names of all defined colors
 * @return list of names
 */
declare function getNames(): X11ColorNames[];

declare const tcolor: TColor;

export {
    getForName,
    getNames,

    tcolor as INDIANRED,
    tcolor as LIGHTCORAL,
    tcolor as SALMON,
    tcolor as DARKSALMON,
    tcolor as LIGHTSALMON,
    tcolor as RED,
    tcolor as CRIMSON,
    tcolor as FIREBRICK,
    tcolor as DARKRED,
    tcolor as PINK,
    tcolor as LIGHTPINK,
    tcolor as HOTPINK,
    tcolor as DEEPPINK,
    tcolor as MEDIUMVIOLETRED,
    tcolor as PALEVIOLETRED,
    tcolor as CORAL,
    tcolor as TOMATO,
    tcolor as ORANGERED,
    tcolor as DARKORANGE,
    tcolor as ORANGE,
    tcolor as GOLD,
    tcolor as YELLOW,
    tcolor as LIGHTYELLOW,
    tcolor as LEMONCHIFFON,
    tcolor as LIGHTGOLDENRODYELLOW,
    tcolor as PAPAYAWHIP,
    tcolor as MOCCASIN,
    tcolor as PEACHPUFF,
    tcolor as PALEGOLDENROD,
    tcolor as KHAKI,
    tcolor as DARKKHAKI,
    tcolor as LAVENDER,
    tcolor as THISTLE,
    tcolor as PLUM,
    tcolor as VIOLET,
    tcolor as ORCHID,
    tcolor as FUCHSIA,
    tcolor as MAGENTA,
    tcolor as MEDIUMORCHID,
    tcolor as MEDIUMPURPLE,
    tcolor as BLUEVIOLET,
    tcolor as DARKVIOLET,
    tcolor as DARKORCHID,
    tcolor as DARKMAGENTA,
    tcolor as PURPLE,
    tcolor as INDIGO,
    tcolor as DARKSLATEBLUE,
    tcolor as SLATEBLUE,
    tcolor as MEDIUMSLATEBLUE,
    tcolor as GREENYELLOW,
    tcolor as CHARTREUSE,
    tcolor as LAWNGREEN,
    tcolor as LIME,
    tcolor as LIMEGREEN,
    tcolor as PALEGREEN,
    tcolor as LIGHTGREEN,
    tcolor as MEDIUMSPRINGGREEN,
    tcolor as SPRINGGREEN,
    tcolor as MEDIUMSEAGREEN,
    tcolor as SEAGREEN,
    tcolor as FORESTGREEN,
    tcolor as GREEN,
    tcolor as DARKGREEN,
    tcolor as YELLOWGREEN,
    tcolor as OLIVEDRAB,
    tcolor as OLIVE,
    tcolor as DARKOLIVEGREEN,
    tcolor as MEDIUMAQUAMARINE,
    tcolor as DARKSEAGREEN,
    tcolor as LIGHTSEAGREEN,
    tcolor as DARKCYAN,
    tcolor as TEAL,
    tcolor as AQUA,
    tcolor as CYAN,
    tcolor as LIGHTCYAN,
    tcolor as PALETURQUOISE,
    tcolor as AQUAMARINE,
    tcolor as TURQUOISE,
    tcolor as MEDIUMTURQUOISE,
    tcolor as DARKTURQUOISE,
    tcolor as CADETBLUE,
    tcolor as STEELBLUE,
    tcolor as LIGHTSTEELBLUE,
    tcolor as POWDERBLUE,
    tcolor as LIGHTBLUE,
    tcolor as SKYBLUE,
    tcolor as LIGHTSKYBLUE,
    tcolor as DEEPSKYBLUE,
    tcolor as DODGERBLUE,
    tcolor as CORNFLOWERBLUE,
    tcolor as ROYALBLUE,
    tcolor as BLUE,
    tcolor as MEDIUMBLUE,
    tcolor as DARKBLUE,
    tcolor as NAVY,
    tcolor as MIDNIGHTBLUE,
    tcolor as CORNSILK,
    tcolor as BLANCHEDALMOND,
    tcolor as BISQUE,
    tcolor as NAVAJOWHITE,
    tcolor as WHEAT,
    tcolor as BURLYWOOD,
    tcolor as TAN,
    tcolor as ROSYBROWN,
    tcolor as SANDYBROWN,
    tcolor as GOLDENROD,
    tcolor as DARKGOLDENROD,
    tcolor as PERU,
    tcolor as CHOCOLATE,
    tcolor as SADDLEBROWN,
    tcolor as SIENNA,
    tcolor as BROWN,
    tcolor as MAROON,
    tcolor as WHITE,
    tcolor as SNOW,
    tcolor as HONEYDEW,
    tcolor as MINTCREAM,
    tcolor as AZURE,
    tcolor as ALICEBLUE,
    tcolor as GHOSTWHITE,
    tcolor as WHITESMOKE,
    tcolor as SEASHELL,
    tcolor as BEIGE,
    tcolor as OLDLACE,
    tcolor as FLORALWHITE,
    tcolor as IVORY,
    tcolor as ANTIQUEWHITE,
    tcolor as LINEN,
    tcolor as LAVENDERBLUSH,
    tcolor as MISTYROSE,
    tcolor as GAINSBORO,
    tcolor as LIGHTGRAY,
    tcolor as SILVER,
    tcolor as DARKGRAY,
    tcolor as GRAY,
    tcolor as DIMGRAY,
    tcolor as LIGHTSLATEGRAY,
    tcolor as SLATEGRAY,
    tcolor as DARKSLATEGRAY,
    tcolor as BLACK,
    tcolor as BARK,
    tcolor as TRANSPARENT
}