declare type X11ColorNamesUpper = "INDIANRED" |
    "LIGHTCORAL" |
    "SALMON" |
    "DARKSALMON" |
    "LIGHTSALMON" |
    "RED" |
    "CRIMSON" |
    "FIREBRICK" |
    "DARKRED" |
    "PINK" |
    "LIGHTPINK" |
    "HOTPINK" |
    "DEEPPINK" |
    "MEDIUMVIOLETRED" |
    "PALEVIOLETRED" |
    "CORAL" |
    "TOMATO" |
    "ORANGERED" |
    "DARKORANGE" |
    "ORANGE" |
    "GOLD" |
    "YELLOW" |
    "LIGHTYELLOW" |
    "LEMONCHIFFON" |
    "LIGHTGOLDENRODYELLOW" |
    "PAPAYAWHIP" |
    "MOCCASIN" |
    "PEACHPUFF" |
    "PALEGOLDENROD" |
    "KHAKI" |
    "DARKKHAKI" |
    "LAVENDER" |
    "THISTLE" |
    "PLUM" |
    "VIOLET" |
    "ORCHID" |
    "FUCHSIA" |
    "MAGENTA" |
    "MEDIUMORCHID" |
    "MEDIUMPURPLE" |
    "BLUEVIOLET" |
    "DARKVIOLET" |
    "DARKORCHID" |
    "DARKMAGENTA" |
    "PURPLE" |
    "INDIGO" |
    "DARKSLATEBLUE" |
    "SLATEBLUE" |
    "MEDIUMSLATEBLUE" |
    "GREENYELLOW" |
    "CHARTREUSE" |
    "LAWNGREEN" |
    "LIME" |
    "LIMEGREEN" |
    "PALEGREEN" |
    "LIGHTGREEN" |
    "MEDIUMSPRINGGREEN" |
    "SPRINGGREEN" |
    "MEDIUMSEAGREEN" |
    "SEAGREEN" |
    "FORESTGREEN" |
    "GREEN" |
    "DARKGREEN" |
    "YELLOWGREEN" |
    "OLIVEDRAB" |
    "OLIVE" |
    "DARKOLIVEGREEN" |
    "MEDIUMAQUAMARINE" |
    "DARKSEAGREEN" |
    "LIGHTSEAGREEN" |
    "DARKCYAN" |
    "TEAL" |
    "AQUA" |
    "CYAN" |
    "LIGHTCYAN" |
    "PALETURQUOISE" |
    "AQUAMARINE" |
    "TURQUOISE" |
    "MEDIUMTURQUOISE" |
    "DARKTURQUOISE" |
    "CADETBLUE" |
    "STEELBLUE" |
    "LIGHTSTEELBLUE" |
    "POWDERBLUE" |
    "LIGHTBLUE" |
    "SKYBLUE" |
    "LIGHTSKYBLUE" |
    "DEEPSKYBLUE" |
    "DODGERBLUE" |
    "CORNFLOWERBLUE" |
    "ROYALBLUE" |
    "BLUE" |
    "MEDIUMBLUE" |
    "DARKBLUE" |
    "NAVY" |
    "MIDNIGHTBLUE" |
    "CORNSILK" |
    "BLANCHEDALMOND" |
    "BISQUE" |
    "NAVAJOWHITE" |
    "WHEAT" |
    "BURLYWOOD" |
    "TAN" |
    "ROSYBROWN" |
    "SANDYBROWN" |
    "GOLDENROD" |
    "DARKGOLDENROD" |
    "PERU" |
    "CHOCOLATE" |
    "SADDLEBROWN" |
    "SIENNA" |
    "BROWN" |
    "MAROON" |
    "WHITE" |
    "SNOW" |
    "HONEYDEW" |
    "MINTCREAM" |
    "AZURE" |
    "ALICEBLUE" |
    "GHOSTWHITE" |
    "WHITESMOKE" |
    "SEASHELL" |
    "BEIGE" |
    "OLDLACE" |
    "FLORALWHITE" |
    "IVORY" |
    "ANTIQUEWHITE" |
    "LINEN" |
    "LAVENDERBLUSH" |
    "MISTYROSE" |
    "GAINSBORO" |
    "LIGHTGRAY" |
    "SILVER" |
    "DARKGRAY" |
    "GRAY" |
    "DIMGRAY" |
    "LIGHTSLATEGRAY" |
    "SLATEGRAY" |
    "DARKSLATEGRAY" |
    "BLACK" |
    "BARK" | 
    "TRANSPARENT";

declare type X11ColorNamesLower = "indianred" |
    "lightcoral" |
    "salmon" |
    "darksalmon" |
    "lightsalmon" |
    "red" |
    "crimson" |
    "firebrick" |
    "darkred" |
    "pink" |
    "lightpink" |
    "hotpink" |
    "deeppink" |
    "mediumvioletred" |
    "palevioletred" |
    "coral" |
    "tomato" |
    "orangered" |
    "darkorange" |
    "orange" |
    "gold" |
    "yellow" |
    "lightyellow" |
    "lemonchiffon" |
    "lightgoldenrodyellow" |
    "papayawhip" |
    "moccasin" |
    "peachpuff" |
    "palegoldenrod" |
    "khaki" |
    "darkkhaki" |
    "lavender" |
    "thistle" |
    "plum" |
    "violet" |
    "orchid" |
    "fuchsia" |
    "magenta" |
    "mediumorchid" |
    "mediumpurple" |
    "blueviolet" |
    "darkviolet" |
    "darkorchid" |
    "darkmagenta" |
    "purple" |
    "indigo" |
    "darkslateblue" |
    "slateblue" |
    "mediumslateblue" |
    "greenyellow" |
    "chartreuse" |
    "lawngreen" |
    "lime" |
    "limegreen" |
    "palegreen" |
    "lightgreen" |
    "mediumspringgreen" |
    "springgreen" |
    "mediumseagreen" |
    "seagreen" |
    "forestgreen" |
    "green" |
    "darkgreen" |
    "yellowgreen" |
    "olivedrab" |
    "olive" |
    "darkolivegreen" |
    "mediumaquamarine" |
    "darkseagreen" |
    "lightseagreen" |
    "darkcyan" |
    "teal" |
    "aqua" |
    "cyan" |
    "lightcyan" |
    "paleturquoise" |
    "aquamarine" |
    "turquoise" |
    "mediumturquoise" |
    "darkturquoise" |
    "cadetblue" |
    "steelblue" |
    "lightsteelblue" |
    "powderblue" |
    "lightblue" |
    "skyblue" |
    "lightskyblue" |
    "deepskyblue" |
    "dodgerblue" |
    "cornflowerblue" |
    "royalblue" |
    "blue" |
    "mediumblue" |
    "darkblue" |
    "navy" |
    "midnightblue" |
    "cornsilk" |
    "blanchedalmond" |
    "bisque" |
    "navajowhite" |
    "wheat" |
    "burlywood" |
    "tan" |
    "rosybrown" |
    "sandybrown" |
    "goldenrod" |
    "darkgoldenrod" |
    "peru" |
    "chocolate" |
    "saddlebrown" |
    "sienna" |
    "brown" |
    "maroon" |
    "white" |
    "snow" |
    "honeydew" |
    "mintcream" |
    "azure" |
    "aliceblue" |
    "ghostwhite" |
    "whitesmoke" |
    "seashell" |
    "beige" |
    "oldlace" |
    "floralwhite" |
    "ivory" |
    "antiquewhite" |
    "linen" |
    "lavenderblush" |
    "mistyrose" |
    "gainsboro" |
    "lightgray" |
    "silver" |
    "darkgray" |
    "gray" |
    "dimgray" |
    "lightslategray" |
    "slategray" |
    "darkslategray" |
    "black" |
    "bark" | 
    "transparent";

declare type X11ColorNames = X11ColorNamesUpper |
    X11ColorNamesLower;

export {
    X11ColorNames
};